version: '3.8'
services:
  db:
    # env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    image: postgres
    container_name: pizzeria_db
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - development
      - test
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # command: bash -c "rm -f tmp/pids/server.pid && bundle install && yarn install --check-files && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: pizzeria_web
    volumes:
      - .:/app
    networks:
      - development
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env.development
    environment:
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
    stdin_open: true
    tty: true
  test:
    image: pizzeria_web
    container_name: pizzeria_test
    volumes:
      - .:/app
    env_file: .env.test
    environment:
      RAILS_ENV: test
    depends_on:
      - db
    networks:
      - test
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
    command: ["rails", "-v"]

volumes:
  postgres:
networks:
  development:
  test:
